### ISSUE TITLE
Custom routes not working

### ISSUE THREAD

**Issue by doijunior** [marmelab/admin-on-rest-demo#31]
~~I tried to use custom routes in my code just like the documentation and didn't worked so I cloned this demo to see how it works. I have looked the routes.js file and notice that it didn't work in the demo too since the links [segments](https://marmelab.com/admin-on-rest-demo/segments) and [configuration](https://marmelab.com/admin-on-rest-demo/configuration) returned 404 not found.

Running on localhost those routes open the dashboard.~~

My Bad. I just noticed that I must follow /#/customRoute pattern. Changing the subject, can I switch that off?

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [admin-on-rest contributing guide](https://github.com/marmelab/admin-on-rest/blob/master/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/admin-on-rest).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/admin-on-rest

And once you get a response, please continue to hang out on the admin-on-rest channel in StackOverflow. That way, you can help newcomers and share your expertise!
