### ISSUE TITLE
CreateButton must pass record id of form

### ISSUE THREAD

**Issue by seejayuu** [marmelab/admin-on-rest-demo#34]
I am using ReferenceManyField to show the items in an order, the typical master/detail database pattern. I am able to edit existing detail records, but can't find a way to add new detail records. I tried the following, but <CreateButton/> doesn't receive {id} like <EditButton/> does. I notice that admin-on-rest-demo allows editing of detail records (reviews of products), but does not allow adding of reviews. Is there a pattern or workaround to do this?

           <SimpleForm>
                <ReferenceManyField label="ITEMS" reference="orderitems" target="orderId">
                    <Datagrid>
                        <CreateButton/> <===== does not pass {id} of form record
                        <EditButton/>    <===== passes {id} of form record
                    </Datagrid>
                </ReferenceManyField>
            </SimpleForm>

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in the [admin-on-rest contributing guide](https://github.com/marmelab/admin-on-rest/blob/master/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/admin-on-rest).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/admin-on-rest

And once you get a response, please continue to hang out on the admin-on-rest channel in StackOverflow. That way, you can help newcomers and share your expertise!
